[phases.setup]
nixPkgs = ['nodejs_18', 'npm']

[phases.install]
cmds = ['cd railway-backend && npm ci --only=production']

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd railway-backend && npm start'