[build]
builder = "nixpacks"
buildCommand = "npm install && cd railway-backend && npm install"

[deploy]
startCommand = "cd railway-backend && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "always"